### ISSUE TITLE
dpotrf error 

### ISSUE THREAD

**Issue by bikeactuary** [cran/spNNGP#1]
I'm getting an error related to cholesky decomposition (dpotrf failed). However, I only get this error with cov.model set to "gaussian" or "matern". The sampling runs for "exponential" and "spherical" with no other changes (except for including tags related to nu for matern). My matrix is positive definite.

I can't share the data but perhaps you could look at this specification. 

    coords <- rough.dedup[, c("lon_jitter", "lat_jitter")] %>% data.matrix()
    starting <- list("phi" = 1, "sigma.sq" = 10, "tau.sq" = 1)
    tuning <- list("phi" = 0.5, "sigma.sq" = 0.5, "tau.sq" = 0.5)
    priors <- list("phi.Unif"=c(3/.5, 3/.01), "sigma.sq.IG"=c(4, 1.5), "tau.sq.IG"=c(2.5, 1.5))
    cov.model <- "gaussian" #change to exponential or spherical and spNNGP runs

    ## standardizing the variable which is being smoothed
    y_mu <- mean(rough.dedup$score)
    y_sd <- sqrt(var(rough.dedup$score))
    rough.dedup$score <- (rough.dedup$score - y_mu) / y_sd

    set.seed(187)
    smoother <- spNNGP(score ~ 1,
                       coords = coords,
                       starting = starting,
                       tuning = tuning,
                       priors = priors,
                       cov.model = cov.model,
                       n.neighbors = 15,
                       n.samples = 500,
                       n.omp.threads = 5,
                       data = rough.dedup,
                       method = "sequential")

Note in the output how the error output strangely restates the formula as "score ~ 11" when I specify "score ~ 1" to get an intercept only model. 

Output:
    
    ----------------------------------------
	    Model description
    ----------------------------------------
    NNGP Sequential model fit with 37794 observations.
    
    Number of covariates 1 (including intercept if specified).
    
    Using the gaussian spatial correlation model.
    
    Using 15 nearest neighbors.
    
    Number of MCMC samples 500.
    
    Priors and hyperpriors:
	    beta flat.
	    sigma.sq IG hyperpriors shape=2.00000 and scale=5.00000
	    tau.sq IG hyperpriors shape=2.00000 and scale=1.00000
	    phi Unif hyperpriors a=3.00000 and b=300.00000
    
    Source compiled with OpenMP support and model fit using 5 thread(s).
    ----------------------------------------
	Building neighbor index
    Building neighbors of neighbor index
    ----------------------------------------
    		Sampling
    ----------------------------------------
    Error in spNNGP((score  ~ 11, coords = coords, , starting = starting, tuning = tuning,  : 
      c++ error: dpotrf failed
    Error during wrapup: no function to return from, jumping to top level

R session crashes following this.  If I don't try to use multiple threads, I still get a dpotrf error, but R session won't crash.

----------------------------------------
	Model description
----------------------------------------
NNGP Sequential model fit with 37794 observations.

Number of covariates 1 (including intercept if specified).

Using the gaussian spatial correlation model.

Using 15 nearest neighbors.

Number of MCMC samples 500.

Priors and hyperpriors:
	beta flat.
	sigma.sq IG hyperpriors shape=2.00000 and scale=5.00000
	tau.sq IG hyperpriors shape=2.00000 and scale=1.00000
	phi Unif hyperpriors a=2.00000 and b=100.00000

Source compiled with OpenMP support and model fit using 1 thread(s).
----------------------------------------
	Building neighbor index
Building neighbors of neighbor index
----------------------------------------
		Sampling
----------------------------------------
Error in spNNGP(score ~ 1, coords = coords, starting = starting, tuning = tuning,  : 
  c++ error: dpotrf failed

**Comment by bikeactuary** [comment]
> cov(rough.dedup[,c("lat_jitter", "lon_jitter")]) %>% is.positive.definite()
    [1] TRUE

just to confirm

**Comment by gaborcsardi** [comment]
Thanks, this is a read-only mirror of CRAN, please see the package authors in the DESCRIPTION file.

**Comment by nngeorgetown** [comment]
> I'm getting an error related to cholesky decomposition (dpotrf failed). However, I only get this error with cov.model set to "gaussian" or "matern". The sampling runs for "exponential" and "spherical" with no other changes (except for including tags related to nu for matern). My matrix is positive definite.
> 
> I can't share the data but perhaps you could look at this specification.
> 
> ```
> coords <- rough.dedup[, c("lon_jitter", "lat_jitter")] %>% data.matrix()
> starting <- list("phi" = 1, "sigma.sq" = 10, "tau.sq" = 1)
> tuning <- list("phi" = 0.5, "sigma.sq" = 0.5, "tau.sq" = 0.5)
> priors <- list("phi.Unif"=c(3/.5, 3/.01), "sigma.sq.IG"=c(4, 1.5), "tau.sq.IG"=c(2.5, 1.5))
> cov.model <- "gaussian" #change to exponential or spherical and spNNGP runs
> 
> ## standardizing the variable which is being smoothed
> y_mu <- mean(rough.dedup$score)
> y_sd <- sqrt(var(rough.dedup$score))
> rough.dedup$score <- (rough.dedup$score - y_mu) / y_sd
> 
> set.seed(187)
> smoother <- spNNGP(score ~ 1,
>                    coords = coords,
>                    starting = starting,
>                    tuning = tuning,
>                    priors = priors,
>                    cov.model = cov.model,
>                    n.neighbors = 15,
>                    n.samples = 500,
>                    n.omp.threads = 5,
>                    data = rough.dedup,
>                    method = "sequential")
> ```
> 
> Note in the output how the error output strangely restates the formula as "score ~ 11" when I specify "score ~ 1" to get an intercept only model.
> 
> Output:
> 
> ```
> ----------------------------------------
>     Model description
> ----------------------------------------
> NNGP Sequential model fit with 37794 observations.
> 
> Number of covariates 1 (including intercept if specified).
> 
> Using the gaussian spatial correlation model.
> 
> Using 15 nearest neighbors.
> 
> Number of MCMC samples 500.
> 
> Priors and hyperpriors:
>     beta flat.
>     sigma.sq IG hyperpriors shape=2.00000 and scale=5.00000
>     tau.sq IG hyperpriors shape=2.00000 and scale=1.00000
>     phi Unif hyperpriors a=3.00000 and b=300.00000
> 
> Source compiled with OpenMP support and model fit using 5 thread(s).
> ----------------------------------------
> Building neighbor index
> Building neighbors of neighbor index
> ----------------------------------------
> 		Sampling
> ----------------------------------------
> Error in spNNGP((score  ~ 11, coords = coords, , starting = starting, tuning = tuning,  : 
>   c++ error: dpotrf failed
> Error during wrapup: no function to return from, jumping to top level
> ```
> 
> R session crashes following this. If I don't try to use multiple threads, I still get a dpotrf error, but R session won't crash.
> 
> ```
> Model description
> ```
> 
> NNGP Sequential model fit with 37794 observations.
> 
> Number of covariates 1 (including intercept if specified).
> 
> Using the gaussian spatial correlation model.
> 
> Using 15 nearest neighbors.
> 
> Number of MCMC samples 500.
> 
> Priors and hyperpriors:
> beta flat.
> sigma.sq IG hyperpriors shape=2.00000 and scale=5.00000
> tau.sq IG hyperpriors shape=2.00000 and scale=1.00000
> phi Unif hyperpriors a=2.00000 and b=100.00000
> 
> ## Source compiled with OpenMP support and model fit using 1 thread(s).
> ```
> Building neighbor index
> ```
> 
> ## Building neighbors of neighbor index
> ```
> 	Sampling
> ```
> 
> Error in spNNGP(score ~ 1, coords = coords, starting = starting, tuning = tuning, :
> c++ error: dpotrf failed

Hi there: I am also having the same issue when using the spNNGP package. Do you have any suggestion on how to solve this issue ? I have about 29000 rows of lat and lon.

Error in spNNGP(y ~ X - 1, coords = coords, starting = starting, method = "response",  : 
  c++ error: dpotrf failed

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the DESCRIPTION file. Thanks!
